/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TabsRouteImport } from './routes/_tabs'
import { Route as TabsIndexRouteImport } from './routes/_tabs.index'
import { Route as TabsAccountRouteImport } from './routes/_tabs.account'
import { Route as TabsBidsRouteImport } from './routes/_tabs.bids'
import { Route as TabsCalendarRouteImport } from './routes/_tabs.calendar'
import { Route as TabsChatRouteImport } from './routes/_tabs.chat'
import { Route as TabsMoreRouteImport } from './routes/_tabs.more'
import { Route as TabsNotificationsRouteImport } from './routes/_tabs.notifications'
import { Route as TabsPlanRouteImport } from './routes/_tabs.plan'
import { Route as TabsProfileRouteImport } from './routes/_tabs.profile'
import { Route as TabsReportsRouteImport } from './routes/_tabs.reports'
import { Route as TabsRequestsRouteImport } from './routes/_tabs.requests'
import { Route as TabsServicemenRouteImport } from './routes/_tabs.servicemen'
import { Route as TabsServicesRouteImport } from './routes/_tabs.services'
import { Route as TabsWithdrawRouteImport } from './routes/_tabs.withdraw'
import { Route as TabsBookingIdRouteImport } from './routes/_tabs.booking.$id'
import { Route as TabsCategoryNameRouteImport } from './routes/_tabs.category.$name'
import { Route as TabsChatIdRouteImport } from './routes/_tabs.chat.$id'

const TabsRoute = TabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsIndexRoute = TabsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TabsRoute,
} as any)
const TabsAccountRoute = TabsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => TabsRoute,
} as any)
const TabsBidsRoute = TabsBidsRouteImport.update({
  id: '/bids',
  path: '/bids',
  getParentRoute: () => TabsRoute,
} as any)
const TabsCalendarRoute = TabsCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => TabsRoute,
} as any)
const TabsChatRoute = TabsChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => TabsRoute,
} as any)
const TabsMoreRoute = TabsMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => TabsRoute,
} as any)
const TabsNotificationsRoute = TabsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => TabsRoute,
} as any)
const TabsPlanRoute = TabsPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => TabsRoute,
} as any)
const TabsProfileRoute = TabsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TabsRoute,
} as any)
const TabsReportsRoute = TabsReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => TabsRoute,
} as any)
const TabsRequestsRoute = TabsRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => TabsRoute,
} as any)
const TabsServicemenRoute = TabsServicemenRouteImport.update({
  id: '/servicemen',
  path: '/servicemen',
  getParentRoute: () => TabsRoute,
} as any)
const TabsServicesRoute = TabsServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => TabsRoute,
} as any)
const TabsWithdrawRoute = TabsWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => TabsRoute,
} as any)
const TabsBookingIdRoute = TabsBookingIdRouteImport.update({
  id: '/booking/$id',
  path: '/booking/$id',
  getParentRoute: () => TabsRoute,
} as any)
const TabsCategoryNameRoute = TabsCategoryNameRouteImport.update({
  id: '/category/$name',
  path: '/category/$name',
  getParentRoute: () => TabsRoute,
} as any)
const TabsChatIdRoute = TabsChatIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TabsChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof TabsIndexRoute
  '/account': typeof TabsAccountRoute
  '/bids': typeof TabsBidsRoute
  '/calendar': typeof TabsCalendarRoute
  '/chat': typeof TabsChatRouteWithChildren
  '/more': typeof TabsMoreRoute
  '/notifications': typeof TabsNotificationsRoute
  '/plan': typeof TabsPlanRoute
  '/profile': typeof TabsProfileRoute
  '/reports': typeof TabsReportsRoute
  '/requests': typeof TabsRequestsRoute
  '/servicemen': typeof TabsServicemenRoute
  '/services': typeof TabsServicesRoute
  '/withdraw': typeof TabsWithdrawRoute
  '/booking/$id': typeof TabsBookingIdRoute
  '/category/$name': typeof TabsCategoryNameRoute
  '/chat/$id': typeof TabsChatIdRoute
}
export interface FileRoutesByTo {
  '/account': typeof TabsAccountRoute
  '/bids': typeof TabsBidsRoute
  '/calendar': typeof TabsCalendarRoute
  '/chat': typeof TabsChatRouteWithChildren
  '/more': typeof TabsMoreRoute
  '/notifications': typeof TabsNotificationsRoute
  '/plan': typeof TabsPlanRoute
  '/profile': typeof TabsProfileRoute
  '/reports': typeof TabsReportsRoute
  '/requests': typeof TabsRequestsRoute
  '/servicemen': typeof TabsServicemenRoute
  '/services': typeof TabsServicesRoute
  '/withdraw': typeof TabsWithdrawRoute
  '/': typeof TabsIndexRoute
  '/booking/$id': typeof TabsBookingIdRoute
  '/category/$name': typeof TabsCategoryNameRoute
  '/chat/$id': typeof TabsChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_tabs': typeof TabsRouteWithChildren
  '/_tabs/account': typeof TabsAccountRoute
  '/_tabs/bids': typeof TabsBidsRoute
  '/_tabs/calendar': typeof TabsCalendarRoute
  '/_tabs/chat': typeof TabsChatRouteWithChildren
  '/_tabs/more': typeof TabsMoreRoute
  '/_tabs/notifications': typeof TabsNotificationsRoute
  '/_tabs/plan': typeof TabsPlanRoute
  '/_tabs/profile': typeof TabsProfileRoute
  '/_tabs/reports': typeof TabsReportsRoute
  '/_tabs/requests': typeof TabsRequestsRoute
  '/_tabs/servicemen': typeof TabsServicemenRoute
  '/_tabs/services': typeof TabsServicesRoute
  '/_tabs/withdraw': typeof TabsWithdrawRoute
  '/_tabs/': typeof TabsIndexRoute
  '/_tabs/booking/$id': typeof TabsBookingIdRoute
  '/_tabs/category/$name': typeof TabsCategoryNameRoute
  '/_tabs/chat/$id': typeof TabsChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/bids'
    | '/calendar'
    | '/chat'
    | '/more'
    | '/notifications'
    | '/plan'
    | '/profile'
    | '/reports'
    | '/requests'
    | '/servicemen'
    | '/services'
    | '/withdraw'
    | '/booking/$id'
    | '/category/$name'
    | '/chat/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/account'
    | '/bids'
    | '/calendar'
    | '/chat'
    | '/more'
    | '/notifications'
    | '/plan'
    | '/profile'
    | '/reports'
    | '/requests'
    | '/servicemen'
    | '/services'
    | '/withdraw'
    | '/'
    | '/booking/$id'
    | '/category/$name'
    | '/chat/$id'
  id:
    | '__root__'
    | '/_tabs'
    | '/_tabs/account'
    | '/_tabs/bids'
    | '/_tabs/calendar'
    | '/_tabs/chat'
    | '/_tabs/more'
    | '/_tabs/notifications'
    | '/_tabs/plan'
    | '/_tabs/profile'
    | '/_tabs/reports'
    | '/_tabs/requests'
    | '/_tabs/servicemen'
    | '/_tabs/services'
    | '/_tabs/withdraw'
    | '/_tabs/'
    | '/_tabs/booking/$id'
    | '/_tabs/category/$name'
    | '/_tabs/chat/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TabsRoute: typeof TabsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/': {
      id: '/_tabs/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof TabsIndexRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/account': {
      id: '/_tabs/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof TabsAccountRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/bids': {
      id: '/_tabs/bids'
      path: '/bids'
      fullPath: '/bids'
      preLoaderRoute: typeof TabsBidsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/calendar': {
      id: '/_tabs/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof TabsCalendarRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/chat': {
      id: '/_tabs/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof TabsChatRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/more': {
      id: '/_tabs/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof TabsMoreRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/notifications': {
      id: '/_tabs/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof TabsNotificationsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/plan': {
      id: '/_tabs/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof TabsPlanRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/profile': {
      id: '/_tabs/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof TabsProfileRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/reports': {
      id: '/_tabs/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof TabsReportsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/requests': {
      id: '/_tabs/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof TabsRequestsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/servicemen': {
      id: '/_tabs/servicemen'
      path: '/servicemen'
      fullPath: '/servicemen'
      preLoaderRoute: typeof TabsServicemenRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/services': {
      id: '/_tabs/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof TabsServicesRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/withdraw': {
      id: '/_tabs/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof TabsWithdrawRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/booking/$id': {
      id: '/_tabs/booking/$id'
      path: '/booking/$id'
      fullPath: '/booking/$id'
      preLoaderRoute: typeof TabsBookingIdRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/category/$name': {
      id: '/_tabs/category/$name'
      path: '/category/$name'
      fullPath: '/category/$name'
      preLoaderRoute: typeof TabsCategoryNameRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/chat/$id': {
      id: '/_tabs/chat/$id'
      path: '/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof TabsChatIdRouteImport
      parentRoute: typeof TabsChatRoute
    }
  }
}

interface TabsChatRouteChildren {
  TabsChatIdRoute: typeof TabsChatIdRoute
}

const TabsChatRouteChildren: TabsChatRouteChildren = {
  TabsChatIdRoute: TabsChatIdRoute,
}

const TabsChatRouteWithChildren = TabsChatRoute._addFileChildren(
  TabsChatRouteChildren,
)

interface TabsRouteChildren {
  TabsAccountRoute: typeof TabsAccountRoute
  TabsBidsRoute: typeof TabsBidsRoute
  TabsCalendarRoute: typeof TabsCalendarRoute
  TabsChatRoute: typeof TabsChatRouteWithChildren
  TabsMoreRoute: typeof TabsMoreRoute
  TabsNotificationsRoute: typeof TabsNotificationsRoute
  TabsPlanRoute: typeof TabsPlanRoute
  TabsProfileRoute: typeof TabsProfileRoute
  TabsReportsRoute: typeof TabsReportsRoute
  TabsRequestsRoute: typeof TabsRequestsRoute
  TabsServicemenRoute: typeof TabsServicemenRoute
  TabsServicesRoute: typeof TabsServicesRoute
  TabsWithdrawRoute: typeof TabsWithdrawRoute
  TabsIndexRoute: typeof TabsIndexRoute
  TabsBookingIdRoute: typeof TabsBookingIdRoute
  TabsCategoryNameRoute: typeof TabsCategoryNameRoute
}

const TabsRouteChildren: TabsRouteChildren = {
  TabsAccountRoute: TabsAccountRoute,
  TabsBidsRoute: TabsBidsRoute,
  TabsCalendarRoute: TabsCalendarRoute,
  TabsChatRoute: TabsChatRouteWithChildren,
  TabsMoreRoute: TabsMoreRoute,
  TabsNotificationsRoute: TabsNotificationsRoute,
  TabsPlanRoute: TabsPlanRoute,
  TabsProfileRoute: TabsProfileRoute,
  TabsReportsRoute: TabsReportsRoute,
  TabsRequestsRoute: TabsRequestsRoute,
  TabsServicemenRoute: TabsServicemenRoute,
  TabsServicesRoute: TabsServicesRoute,
  TabsWithdrawRoute: TabsWithdrawRoute,
  TabsIndexRoute: TabsIndexRoute,
  TabsBookingIdRoute: TabsBookingIdRoute,
  TabsCategoryNameRoute: TabsCategoryNameRoute,
}

const TabsRouteWithChildren = TabsRoute._addFileChildren(TabsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  TabsRoute: TabsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
