import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState, type ReactNode } from "react";
import {
  ArrowLeft, ArrowRight, Bell, Bookmark, CalendarDays, Check, ChevronDown,
  ChevronRight, CircleHelp, Clock3, CreditCard, Gift, Globe2, Heart, Home,
  Inbox, Languages, LifeBuoy, MapPin, Menu, MessageCircle, Minus, Moon,
  Navigation, PackageCheck, Phone, Plus, Search, Send, Settings, ShieldCheck,
  ShoppingBag, SlidersHorizontal, Sparkles, Star, Tag, Trash2, UserRound,
  WalletCards, Wrench, X, Zap, type LucideIcon,
} from "lucide-react";
import cleaningImage from "../assets/service-cleaning.jpg";
import acImage from "../assets/service-ac.jpg";
import plumbingImage from "../assets/service-plumbing.jpg";
import beautyImage from "../assets/service-beauty.jpg";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "nest. — Home services, thoughtfully done" },
      { name: "description", content: "Book trusted home cleaning, repairs, beauty and maintenance professionals near you." },
      { property: "og:title", content: "nest. — Home services, thoughtfully done" },
      { property: "og:description", content: "Trusted professionals for every corner of your home." },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: Index,
});

type Tab = "home" | "services" | "bookings" | "cart" | "account";
type Screen = Tab | "service" | "filter" | "checkout" | "payment" | "success" | "booking" | "provider" | "offers" | "coupons" | "favorites" | "profile" | "settings" | "inbox" | "chat" | "notifications" | "wallet" | "refer" | "support" | "areas" | "addresses" | "language" | "signin" | "signup" | "otp" | "forgot" | "location" | "categories" | "post" | "posts" | "policy" | "state";

type Service = { id: number; name: string; category: string; price: number; rating: string; reviews: string; image: string; duration: string };

const services: Service[] = [
  { id: 1, name: "Full home deep cleaning", category: "Cleaning", price: 2499, rating: "4.89", reviews: "8.2k", image: cleaningImage, duration: "4–5 hrs" },
  { id: 2, name: "AC service & repair", category: "AC & Appliance", price: 499, rating: "4.85", reviews: "12k", image: acImage, duration: "60 mins" },
  { id: 3, name: "Plumbing repair", category: "Repairs", price: 299, rating: "4.82", reviews: "5.4k", image: plumbingImage, duration: "45 mins" },
  { id: 4, name: "Glow facial at home", category: "Salon", price: 899, rating: "4.91", reviews: "3.1k", image: beautyImage, duration: "75 mins" },
];

const categories: Array<{ name: string; icon: LucideIcon }> = [
  { name: "Cleaning", icon: Sparkles }, { name: "AC repair", icon: Zap },
  { name: "Plumber", icon: Wrench }, { name: "Salon", icon: UserRound },
  { name: "Electrician", icon: Zap }, { name: "Painting", icon: Home },
  { name: "Appliances", icon: Settings }, { name: "More", icon: Menu },
];

const accountItems: Array<{ label: string; icon: LucideIcon; screen: Screen }> = [
  { label: "Inbox", icon: Inbox, screen: "inbox" }, { label: "Profile", icon: UserRound, screen: "profile" },
  { label: "Bookings", icon: CalendarDays, screen: "bookings" }, { label: "Offers", icon: Tag, screen: "offers" },
  { label: "Vouchers", icon: Gift, screen: "coupons" }, { label: "My favorites", icon: Heart, screen: "favorites" },
  { label: "My posts", icon: MessageCircle, screen: "posts" }, { label: "Wallet", icon: WalletCards, screen: "wallet" },
  { label: "Refer & earn", icon: Gift, screen: "refer" }, { label: "Language", icon: Languages, screen: "language" },
  { label: "Settings", icon: Settings, screen: "settings" },
];

function Index() {
  const [screen, setScreen] = useState<Screen>("home");
  const [history, setHistory] = useState<Screen[]>([]);
  const [selectedService, setSelectedService] = useState<Service>(services[0]);
  const [cartCount, setCartCount] = useState(1);
  const [favoriteIds, setFavoriteIds] = useState<number[]>([2]);
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("All");
  const [dark, setDark] = useState(false);
  const [sheet, setSheet] = useState<"search" | "book" | "location" | null>(null);
  const [toast, setToast] = useState("");

  const navigate = (next: Screen) => { setHistory((old) => [...old, screen]); setScreen(next); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const back = () => { const previous = history.at(-1) ?? "home"; setHistory((old) => old.slice(0, -1)); setScreen(previous); };
  const tabNavigate = (tab: Tab) => { setHistory([]); setScreen(tab); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 2200); };
  const openService = (service: Service) => { setSelectedService(service); navigate("service"); };
  const toggleFavorite = (id: number) => setFavoriteIds((old) => old.includes(id) ? old.filter((item) => item !== id) : [...old, id]);

  const filteredServices = useMemo(() => services.filter((item) =>
    (category === "All" || item.category.includes(category) || (category === "Repairs" && item.category === "Repairs")) &&
    item.name.toLowerCase().includes(query.toLowerCase())), [category, query]);

  const props = { navigate, back, notify, openService, toggleFavorite, favoriteIds, cartCount, setCartCount, selectedService, query, setQuery, category, setCategory, filteredServices, dark, setDark, setSheet };
  const pages: Record<Screen, ReactNode> = {
    home: <HomeScreen {...props} />,
    services: <ServicesScreen {...props} />,
    bookings: <BookingsScreen {...props} />,
    cart: <CartScreen {...props} />,
    account: <AccountScreen {...props} />,
    service: <ServiceScreen {...props} />,
    filter: <FilterScreen {...props} />,
    checkout: <CheckoutScreen {...props} />,
    payment: <PaymentScreen {...props} />,
    success: <SuccessScreen {...props} />,
    booking: <BookingScreen {...props} />,
    provider: <ProviderScreen {...props} />,
    offers: <OffersScreen {...props} />,
    coupons: <CouponsScreen {...props} />,
    favorites: <FavoritesScreen {...props} />,
    profile: <ProfileScreen {...props} />,
    settings: <SettingsScreen {...props} />,
    inbox: <InboxScreen {...props} />,
    chat: <ChatScreen {...props} />,
    notifications: <NotificationsScreen {...props} />,
    wallet: <WalletScreen {...props} />,
    refer: <ReferScreen {...props} />,
    support: <SupportScreen {...props} />,
    areas: <AreasScreen {...props} />,
    addresses: <AddressesScreen {...props} />,
    language: <LanguageScreen {...props} />,
    signin: <AuthScreen mode="signin" {...props} />,
    signup: <AuthScreen mode="signup" {...props} />,
    otp: <OtpScreen {...props} />,
    forgot: <ForgotScreen {...props} />,
    location: <LocationScreen {...props} />,
    categories: <CategoriesScreen {...props} />,
    post: <PostScreen {...props} />,
    posts: <PostsScreen {...props} />,
    policy: <PolicyScreen {...props} />,
    state: <StatesScreen {...props} />,
  };
  const main = (["home", "services", "bookings", "cart", "account"] as Screen[]).includes(screen);

  return (
    <div className={dark ? "dark" : ""}>
      <main className="app-shell">
        <div className="app-content">{pages[screen]}</div>
        {main && <BottomNav active={screen as Tab} onChange={tabNavigate} count={cartCount} />}
        {sheet && <Sheet type={sheet} close={() => setSheet(null)} {...props} />}
        {toast && <div className="toast"><Check size={16} />{toast}</div>}
      </main>
    </div>
  );
}

type PageProps = any;

function Brand() { return <div className="brand"><span className="brand-mark">n.</span><strong>nest.</strong></div>; }
function IconButton({ children, label, onClick, filled = false }: { children: ReactNode; label: string; onClick?: () => void; filled?: boolean }) { return <button aria-label={label} title={label} className={filled ? "icon-btn icon-btn-filled" : "icon-btn"} onClick={onClick}>{children}</button>; }
function Button({ children, onClick, variant = "primary", disabled = false }: { children: ReactNode; onClick?: () => void; variant?: "primary" | "outline" | "ghost" | "danger"; disabled?: boolean }) { return <button className={`button button-${variant}`} onClick={onClick} disabled={disabled}>{children}</button>; }
function PageHeader({ title, back, action }: { title: string; back: () => void; action?: ReactNode }) { return <header className="page-header"><IconButton label="Go back" onClick={back}><ArrowLeft size={20} /></IconButton><h1>{title}</h1><div className="header-action">{action}</div></header>; }
function SectionTitle({ title, action, onClick }: { title: string; action?: string; onClick?: () => void }) { return <div className="section-title"><h2>{title}</h2>{action && <button onClick={onClick}>{action}<ArrowRight size={15} /></button>}</div>; }

function HomeScreen({ navigate, openService, favoriteIds, toggleFavorite, setSheet }: PageProps) {
  return <div className="screen home-screen">
    <header className="home-header"><Brand/><div className="header-buttons"><IconButton label="Notifications" onClick={() => navigate("notifications")}><Bell size={19}/><span className="unread"/></IconButton><IconButton label="Favorites" onClick={() => navigate("favorites")}><Heart size={19}/></IconButton></div></header>
    <button className="location-pill" onClick={() => setSheet("location")}><MapPin size={15}/><span><small>Home</small> 12, Indiranagar, Bengaluru</span><ChevronDown size={15}/></button>
    <div className="greeting"><p>Good afternoon, Aanya</p><h1>What can we help<br/>with today?</h1></div>
    <button className="search-box" onClick={() => setSheet("search")}><Search size={19}/><span>Search cleaning, AC, plumber…</span></button>
    <div className="category-grid">{categories.map(({ name, icon: Icon }) => <button key={name} onClick={() => name === "More" ? navigate("categories") : navigate("services")}><span><Icon size={21}/></span><b>{name}</b></button>)}</div>
    <button className="hero-card" onClick={() => openService(services[0])}><img src={cleaningImage} alt="Professional home deep cleaning" width={1200} height={800}/><div className="hero-copy"><small>MOST BOOKED</small><h2>Deep clean.<br/>Fresh start.</h2><span>Book now · ₹2,499 <ArrowRight size={15}/></span></div></button>
    <SectionTitle title="Popular near you" action="See all" onClick={() => navigate("services")}/>
    <div className="service-list">{services.slice(0,3).map((service) => <ServiceRow key={service.id} service={service} open={() => openService(service)} favorite={favoriteIds.includes(service.id)} toggle={() => toggleFavorite(service.id)} />)}</div>
    <button className="campaign" onClick={() => navigate("offers")}><div><small>NEW CUSTOMER</small><strong>₹200 off your first booking</strong><span>Use code NEST200</span></div><div className="campaign-badge">20%</div></button>
    <div className="dots"><span className="active"/><span/><span/></div>
    <SectionTitle title="Why choose nest." />
    <div className="trust-grid"><Trust icon={ShieldCheck} title="Verified pros" text="Background checked"/><Trust icon={Tag} title="Upfront pricing" text="No hidden charges"/><Trust icon={PackageCheck} title="7-day warranty" text="We've got you covered"/><Trust icon={LifeBuoy} title="Real support" text="Help when you need it"/></div>
    <button className="offer-strip" onClick={() => navigate("offers")}><span><Tag size={20}/></span><div><small>SPECIAL OFFER</small><b>See current offers</b></div><ArrowRight size={20}/></button>
    <SectionTitle title="All services" action="See all" onClick={() => navigate("services")}/>
    <div className="service-list">{services.map((service) => <ServiceRow key={service.id} service={service} open={() => openService(service)} favorite={favoriteIds.includes(service.id)} toggle={() => toggleFavorite(service.id)} />)}</div>
    <SectionTitle title="Top professionals" action="View all" onClick={() => navigate("provider")}/>
    <button className="provider-preview" onClick={() => navigate("provider")}><div className="avatar">RK</div><div><b>Rahul Kumar</b><span><Star size={13} fill="currentColor"/> 4.92 · 6 years experience</span></div><ChevronRight/></button>
  </div>;
}

function ServiceRow({ service, open, favorite, toggle }: { service: Service; open: () => void; favorite: boolean; toggle: () => void }) { return <div className="service-row"><button className="service-main" onClick={open}><img src={service.image} alt={service.name} loading="lazy" width={180} height={180}/><div><small>{service.category}</small><b>{service.name}</b><span><Star size={12} fill="currentColor"/> {service.rating} · {service.reviews}</span><strong>₹{service.price.toLocaleString("en-IN")} onwards</strong></div></button><button className="save-btn" aria-label="Save service" onClick={toggle}><Bookmark size={18} fill={favorite ? "currentColor" : "none"}/></button></div>; }
function Trust({ icon: Icon, title, text }: { icon: LucideIcon; title: string; text: string }) { return <div className="trust-item"><span><Icon size={20}/></span><b>{title}</b><small>{text}</small></div>; }

function ServicesScreen({ navigate, openService, favoriteIds, toggleFavorite, query, setQuery, category, setCategory, filteredServices }: PageProps) { const chips = ["All", "Cleaning", "AC & Appliance", "Repairs", "Salon"]; return <div className="screen">
  <div className="search-header"><Brand/><IconButton label="Filter" onClick={() => navigate("filter")}><SlidersHorizontal size={19}/></IconButton></div>
  <label className="search-input"><Search size={19}/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="What service do you need?"/>{query && <button onClick={() => setQuery("")}><X size={16}/></button>}</label>
  <div className="chips">{chips.map((chip) => <button className={category === chip ? "chip active" : "chip"} onClick={() => setCategory(chip)} key={chip}>{chip}</button>)}</div>
  <div className="result-row"><b>{filteredServices.length} services found</b><button onClick={() => navigate("filter")}>Sort & filter <SlidersHorizontal size={15}/></button></div>
  {filteredServices.length ? <div className="service-list large">{filteredServices.map((service: Service) => <ServiceRow key={service.id} service={service} open={() => openService(service)} favorite={favoriteIds.includes(service.id)} toggle={() => toggleFavorite(service.id)}/>)}</div> : <Empty title="No services found" text="Try a different search or remove a filter."/>}
  <div className="subtle-banner"><ShieldCheck/><div><b>nest. protection</b><span>Every booking includes service warranty</span></div></div>
  </div>; }

function ServiceScreen({ back, selectedService, favoriteIds, toggleFavorite, cartCount, setSheet }: PageProps) { return <div className="detail-screen">
  <div className="service-hero"><img src={selectedService.image} alt={selectedService.name}/><div className="hero-actions"><IconButton label="Back" onClick={back}><ArrowLeft/></IconButton><div><IconButton label="Save" onClick={() => toggleFavorite(selectedService.id)}><Heart fill={favoriteIds.includes(selectedService.id) ? "currentColor" : "none"}/></IconButton><IconButton label="Cart"><ShoppingBag/><em>{cartCount}</em></IconButton></div></div></div>
  <div className="screen detail-body"><small className="eyebrow">{selectedService.category}</small><h1>{selectedService.name}</h1><div className="rating-line"><span><Star size={14} fill="currentColor"/> {selectedService.rating}</span><u>{selectedService.reviews} reviews</u><span><Clock3 size={14}/> {selectedService.duration}</span></div>
  <div className="price-band"><div><small>Starts at</small><b>₹{selectedService.price.toLocaleString("en-IN")}</b></div><span>Pay after service</span></div>
  <SectionTitle title="About this service"/><p className="body-copy">A meticulous, professional service delivered by background-verified experts. We bring everything needed and leave your space better than we found it.</p>
  <div className="warranty"><ShieldCheck/><div><b>7-day service warranty</b><span>Free revisit if something isn't right</span></div><ChevronRight/></div>
  <SectionTitle title="Photos & videos" action="See all"/><div className="gallery"><img src={selectedService.image} alt="Service view"/><img src={cleaningImage} alt="Service result"/></div>
  <SectionTitle title="Ratings & reviews" action="View all"/><div className="review-summary"><strong>{selectedService.rating}</strong><div><div className="stars">★★★★★</div><span>Based on {selectedService.reviews} verified bookings</span></div></div><Review/>
  </div><div className="sticky-action"><Button onClick={() => setSheet("book")}>Book now · ₹{selectedService.price.toLocaleString("en-IN")}</Button></div>
  </div>; }

function Review() { return <div className="review"><div className="review-head"><div className="avatar small">PS</div><div><b>Priya Sharma</b><span>3 days ago</span></div><strong><Star size={11} fill="currentColor"/> 5</strong></div><p>Professional, punctual and very thorough. The difference was visible immediately.</p></div>; }

function CartScreen({ navigate, cartCount, setCartCount }: PageProps) { return <div className="screen"><div className="simple-title"><h1>Your cart</h1><span>{cartCount} service</span></div><div className="cart-card"><img src={cleaningImage} alt="Deep cleaning"/><div><small>Cleaning</small><b>Full home deep cleaning</b><span>2 BHK · {"Tomorrow, 10:00 AM"}</span><strong>₹2,499</strong></div><div className="stepper"><button onClick={() => setCartCount(Math.max(1, cartCount - 1))}><Minus/></button><b>{cartCount}</b><button onClick={() => setCartCount(cartCount + 1)}><Plus/></button></div></div><button className="add-more" onClick={() => navigate("services")}><Plus size={17}/> Add more services</button><label className="coupon-input"><Tag/><input placeholder="Enter coupon code"/><button onClick={() => navigate("coupons")}>View offers</button></label><PriceSummary/><div className="safety-note"><ShieldCheck/><p><b>Your booking is protected</b><span>Verified professional · 7-day warranty</span></p></div><Button onClick={() => navigate("checkout")}>Checkout · ₹2,748</Button></div>; }
function PriceSummary() { return <div className="price-summary"><h3>Payment summary</h3><p><span>Item total</span><b>₹2,499</b></p><p><span>Taxes & fee</span><b>₹249</b></p><p className="saving"><span>Coupon discount</span><b>− ₹200</b></p><hr/><p className="total"><span>Amount to pay</span><b>₹2,548</b></p></div>; }

function CheckoutScreen({ back, navigate }: PageProps) { const [day, setDay] = useState(1); const [time, setTime] = useState("10:00 AM"); return <div className="screen"><PageHeader title="Address & schedule" back={back}/><Progress current={1}/><SectionTitle title="Service address"/><button className="selection-card selected"><span className="radio checked"><Check/></span><div><b>Home</b><p>12, 3rd Cross Road, Indiranagar<br/>Bengaluru 560038</p></div><small>EDIT</small></button><button className="add-more"><Plus/> Add a new address</button><SectionTitle title="Choose a day"/><div className="date-row">{["Today|29", "Tomorrow|30", "Thu|01", "Fri|02"].map((d, i) => { const [name, number] = d.split("|"); return <button key={d} onClick={() => setDay(i)} className={day === i ? "date active" : "date"}><small>{name}</small><b>{number}</b></button>})}</div><SectionTitle title="Pick a time"/><div className="time-grid">{["8:00 AM", "10:00 AM", "12:00 PM", "2:00 PM", "4:00 PM", "6:00 PM"].map(t => <button key={t} className={time === t ? "time active" : "time"} onClick={() => setTime(t)}>{t}</button>)}</div><div className="sticky-spacer"/><Button onClick={() => navigate("payment")}>Continue to payment</Button></div>; }
function Progress({ current }: { current: number }) { return <div className="progress"><span className={current >= 1 ? "active" : ""}>1</span><i/><span className={current >= 2 ? "active" : ""}>2</span><i/><span className={current >= 3 ? "active" : ""}>3</span><div className="progress-labels"><b>Schedule</b><b>Payment</b><b>Confirmed</b></div></div>; }
function PaymentScreen({ back, navigate }: PageProps) { const [pay, setPay] = useState("Cash after service"); return <div className="screen"><PageHeader title="Payment" back={back}/><Progress current={2}/><div className="booking-mini"><CalendarDays/><div><small>SERVICE APPOINTMENT</small><b>Tomorrow, 10:00 AM</b><span>Home · Indiranagar</span></div></div><SectionTitle title="Select payment method"/><div className="selection-list">{[["Cash after service", WalletCards], ["UPI / digital wallet", Zap], ["Credit or debit card", CreditCard]].map(([label, Icon]) => <button key={label as string} onClick={() => setPay(label as string)}><span className="menu-icon"><Icon size={19}/></span><b>{label as string}</b><span className={pay === label ? "radio checked" : "radio"}>{pay === label && <Check/>}</span></button>)}</div><PriceSummary/><Button onClick={() => navigate("success")}>Place booking · ₹2,548</Button></div>; }
function SuccessScreen({ navigate }: PageProps) { return <div className="success-screen"><div className="success-mark"><Check/></div><small>BOOKING CONFIRMED</small><h1>Your home is in<br/>good hands.</h1><p>We've received your booking. A professional will be assigned shortly.</p><div className="booking-ticket"><span>BOOKING ID</span><strong>#NE384921</strong><hr/><p><CalendarDays/> Tomorrow, 30 Sep</p><p><Clock3/> 10:00 AM</p><p><MapPin/> Home · Indiranagar</p></div><Button onClick={() => navigate("booking")}>Track booking</Button><Button variant="ghost" onClick={() => navigate("home")}>Back to home</Button></div>; }

function BookingsScreen({ navigate }: PageProps) { const [tab, setTab] = useState("Ongoing"); return <div className="screen"><div className="simple-title"><h1>Bookings</h1><IconButton label="Help" onClick={() => navigate("support")}><CircleHelp/></IconButton></div><div className="tab-row">{["Ongoing", "Completed", "Canceled"].map(t => <button onClick={() => setTab(t)} className={tab === t ? "active" : ""} key={t}>{t}</button>)}</div>{tab === "Ongoing" ? <button className="booking-card" onClick={() => navigate("booking")}><div className="booking-status"><span>PROFESSIONAL ASSIGNED</span><small>#NE384921</small></div><div className="booking-service"><img src={cleaningImage} alt="Cleaning"/><div><b>Full home deep cleaning</b><span>Tomorrow · 10:00 AM</span><strong>₹2,548</strong></div><ChevronRight/></div><div className="booking-progress"><i className="done"/><i className="done"/><i/><i/></div><p>Rahul is preparing for your service</p></button> : tab === "Completed" ? <button className="booking-card"><div className="booking-status"><span>COMPLETED</span><small>#NE371024</small></div><div className="booking-service"><img src={acImage} alt="AC service"/><div><b>AC service & repair</b><span>16 Sep · 2:00 PM</span><strong>₹699</strong></div><ChevronRight/></div><Button variant="outline">Book again</Button></button> : <Empty title="No canceled bookings" text="Bookings you cancel will show up here."/>}</div>; }
function BookingScreen({ back, navigate }: PageProps) { return <div className="screen"><PageHeader title="Booking details" back={back} action={<IconButton label="Support" onClick={() => navigate("support")}><CircleHelp/></IconButton>}/><div className="status-hero"><small>PROFESSIONAL ASSIGNED</small><h2>Everything's on track</h2><p>Rahul will arrive tomorrow by 10:00 AM</p></div><div className="timeline">{["Booking confirmed", "Professional assigned", "Service in progress", "Completed"].map((x,i) => <div className={i < 2 ? "done" : ""} key={x}><span>{i < 2 && <Check/>}</span><p><b>{x}</b><small>{i === 0 ? "Today, 11:42 AM" : i === 1 ? "Today, 12:10 PM" : "Pending"}</small></p></div>)}</div><button className="provider-card" onClick={() => navigate("provider")}><div className="avatar">RK</div><div><small>YOUR PROFESSIONAL</small><b>Rahul Kumar</b><span><Star size={12} fill="currentColor"/> 4.92 · 1.2k jobs</span></div><IconButton label="Call"><Phone/></IconButton><IconButton label="Chat" onClick={() => navigate("chat")}><MessageCircle/></IconButton></button><InfoGroup/><PriceSummary/><div className="dual-actions"><Button variant="outline">Cancel booking</Button><Button onClick={() => navigate("cart")}>Repeat</Button></div></div>; }
function InfoGroup() { return <div className="info-group"><p><CalendarDays/><span><small>SCHEDULE</small><b>Tomorrow, 10:00 AM</b></span></p><p><MapPin/><span><small>ADDRESS</small><b>12, 3rd Cross Road, Indiranagar</b></span></p><p><CreditCard/><span><small>PAYMENT</small><b>Cash after service</b></span></p></div>; }

function AccountScreen({ navigate }: PageProps) { return <div className="screen"><div className="simple-title"><h1>Account</h1><IconButton label="Notifications" onClick={() => navigate("notifications")}><Bell/></IconButton></div><button className="profile-card" onClick={() => navigate("profile")}><div className="profile-avatar">AS</div><div><b>Aanya Sharma</b><span>View or edit profile</span></div><ArrowRight/></button><div className="menu-card">{accountItems.map(({label, icon: Icon, screen}) => <button key={label} onClick={() => navigate(screen)}><span className="menu-icon"><Icon size={18}/></span><b>{label}</b>{label === "Inbox" && <em>2</em>}<ChevronRight/></button>)}</div><div className="menu-card">{[["Service area", MapPin, "areas"], ["Help & support", LifeBuoy, "support"], ["Become a professional", Wrench, "provider"], ["About nest.", CircleHelp, "policy"], ["Terms & privacy", ShieldCheck, "policy"]].map(([label, Icon, target]) => <button key={label as string} onClick={() => navigate(target as Screen)}><span className="menu-icon"><Icon size={18}/></span><b>{label as string}</b><ChevronRight/></button>)}</div><button className="logout" onClick={() => navigate("signin")}>Log out</button><footer>nest. · v1.0.0</footer></div>; }

function FilterScreen({ back, notify }: PageProps) { const [sort, setSort] = useState("Recommended"); const [rating, setRating] = useState("4★ & above"); return <div className="screen"><PageHeader title="Sort & filter" back={back} action={<button className="text-action" onClick={() => notify("Filters reset")}>Reset</button>}/><SectionTitle title="Sort by"/><div className="option-grid">{["Recommended", "Top rated", "Price: low to high", "Newest"].map(x => <button onClick={() => setSort(x)} className={sort === x ? "active" : ""} key={x}>{x}</button>)}</div><SectionTitle title="Price range"/><div className="range-label"><b>₹199</b><b>₹5,000+</b></div><input className="range" type="range" min="199" max="5000" defaultValue="3500"/><SectionTitle title="Rating"/><div className="option-grid rating-options">{["5★ only", "4★ & above", "3★ & above"].map(x => <button onClick={() => setRating(x)} className={rating === x ? "active" : ""} key={x}>{x}</button>)}</div><SectionTitle title="Categories"/><div className="check-list">{categories.slice(0,6).map(({name}) => <label key={name}><input type="checkbox" defaultChecked={name === "Cleaning"}/><span>{name}</span></label>)}</div><Button onClick={() => {notify("Filters applied"); back();}}>Show 32 services</Button></div>; }

function OffersScreen({ back, openService }: PageProps) { return <div className="screen"><PageHeader title="Offers" back={back}/><div className="black-hero"><Tag/><small>LIMITED TIME</small><h2>A little care<br/>on us.</h2><p>Save up to 30% on selected home services this week.</p></div><SectionTitle title="Offers for you"/>{services.slice(0,3).map((s, i) => <button className="offer-card" key={s.id} onClick={() => openService(s)}><span>{i === 0 ? "25% OFF" : i === 1 ? "₹200 OFF" : "15% OFF"}</span><div><b>{s.name}</b><small>Use code {i === 0 ? "CLEAN25" : "NEST200"}</small></div><ChevronRight/></button>)}</div>; }
function CouponsScreen({ back, notify }: PageProps) { return <div className="screen"><PageHeader title="Vouchers & coupons" back={back}/>{["NEST200|₹200 off|On your first service · Min. order ₹699", "CLEAN25|25% off|On deep cleaning · Up to ₹500", "WELCOME10|10% off|Valid on all home services"].map(x => { const [code, off, terms] = x.split("|"); return <div className="coupon-card" key={code}><div><Tag/><span><small>{off}</small><b>{code}</b></span></div><p>{terms}</p><button onClick={() => notify(`${code} applied`)}>APPLY</button></div>})}</div>; }
function FavoritesScreen({ back, favoriteIds, toggleFavorite, openService }: PageProps) { const list = services.filter(s => favoriteIds.includes(s.id)); return <div className="screen"><PageHeader title="My favorites" back={back}/><div className="tab-row"><button className="active">Services</button><button>Professionals</button></div>{list.length ? <div className="service-list large">{list.map(s => <ServiceRow key={s.id} service={s} open={() => openService(s)} favorite toggle={() => toggleFavorite(s.id)}/>)}</div> : <Empty title="Nothing saved yet" text="Tap the bookmark on a service you love."/>}</div>; }
function ProviderScreen({ back, openService }: PageProps) { return <div className="screen provider-page"><PageHeader title="Professional" back={back}/><div className="provider-cover"><img src={cleaningImage} alt="Professional at work"/><div className="big-avatar">RK</div></div><div className="provider-name"><h1>Rahul Kumar</h1><span><Star fill="currentColor"/> 4.92 · 1,248 jobs</span><p><MapPin/> 1.8 km away · Bengaluru</p></div><div className="stat-row"><div><b>6 yrs</b><span>Experience</span></div><div><b>98%</b><span>On-time</span></div><div><b>4.92</b><span>Rating</span></div></div><SectionTitle title="About"/><p className="body-copy">Certified home care specialist known for meticulous work, punctuality and clear communication.</p><SectionTitle title="Services"/>{services.slice(0,2).map(s => <ServiceRow key={s.id} service={s} open={() => openService(s)} favorite={false} toggle={() => {}}/>)}</div>; }

function ProfileScreen({ back, notify }: PageProps) { return <div className="screen"><PageHeader title="Profile" back={back}/><div className="profile-editor"><div className="profile-avatar large">AS</div><button>Change photo</button></div><FormField label="Full name" value="Aanya Sharma"/><FormField label="Phone number" value="+91 98765 43210"/><FormField label="Email address" value="aanya@example.com"/><Button onClick={() => notify("Profile updated")}>Save changes</Button></div>; }
function FormField({ label, value, placeholder }: { label: string; value?: string; placeholder?: string }) { return <label className="form-field"><span>{label}</span><input defaultValue={value} placeholder={placeholder}/></label>; }
function SettingsScreen({ back, dark, setDark, notify }: PageProps) { return <div className="screen"><PageHeader title="Settings" back={back}/><div className="settings-list"><ToggleRow icon={Moon} title="Dark mode" text="Reduce glare at night" on={dark} toggle={() => setDark(!dark)}/><ToggleRow icon={Bell} title="Booking updates" text="Status and reminder alerts" on toggle={() => notify("Notification setting updated")}/><ToggleRow icon={Gift} title="Offers & updates" text="Deals picked for you" on={false} toggle={() => notify("Notification setting updated")}/></div><button className="delete-account"><Trash2/> Delete account</button></div>; }
function ToggleRow({icon: Icon, title, text, on, toggle}: {icon: LucideIcon; title: string; text: string; on: boolean; toggle: () => void}) { return <div className="toggle-row"><span className="menu-icon"><Icon/></span><div><b>{title}</b><small>{text}</small></div><button aria-label={`Toggle ${title}`} className={on ? "switch on" : "switch"} onClick={toggle}><i/></button></div>; }

function InboxScreen({ back, navigate }: PageProps) { return <div className="screen"><PageHeader title="Inbox" back={back}/><div className="tab-row"><button className="active">Professionals</button></div>{[["RK", "Rahul Kumar", "I’ll arrive by 10 AM tomorrow.", "2m"], ["NS", "nest. Support", "Your refund has been processed.", "1d"]].map((x,i) => <button className="conversation" key={x[1]} onClick={() => navigate("chat")}><div className="avatar">{x[0]}</div><div><b>{x[1]}</b><span>{x[2]}</span></div><small>{x[3]}{i === 0 && <i/>}</small></button>)}</div>; }
function ChatScreen({ back }: PageProps) { const [message, setMessage] = useState(""); const [messages, setMessages] = useState(["Hi Aanya, I’ll arrive by 10 AM tomorrow.", "Perfect, thank you!"]); return <div className="chat-screen"><div className="chat-header"><IconButton label="Back" onClick={back}><ArrowLeft/></IconButton><div className="avatar small">RK</div><div><b>Rahul Kumar</b><span>Usually replies in minutes</span></div><IconButton label="Call"><Phone/></IconButton></div><div className="messages"><div className="day-label">TODAY</div>{messages.map((m,i) => <div key={`${m}-${i}`} className={i % 2 ? "message mine" : "message"}>{m}<small>{i ? "11:46" : "11:42"}</small></div>)}</div><form className="message-input" onSubmit={(e) => {e.preventDefault(); if(message.trim()){setMessages([...messages, message]); setMessage("");}}}><button type="button"><Plus/></button><input value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Write a message…"/><button type="submit"><Send/></button></form></div>; }
function NotificationsScreen({ back }: PageProps) { return <div className="screen"><PageHeader title="Notifications" back={back} action={<button className="text-action">Read all</button>}/>{["TODAY|Professional assigned|Rahul will arrive tomorrow at 10:00 AM", "TODAY|Booking confirmed|Your booking #NE384921 is confirmed", "YESTERDAY|A fresh offer for you|Save 25% on deep cleaning this week"].map((x,i) => { const [date,title,text] = x.split("|"); return <div key={title}>{(i === 0 || i === 2) && <h3 className="date-label">{date}</h3>}<div className="notification"><span><Bell/></span><div><b>{title}</b><p>{text}</p><small>{i === 0 ? "2 mins ago" : "1 day ago"}</small></div>{i === 0 && <i/>}</div></div>})}</div>; }
function WalletScreen({ back }: PageProps) { return <div className="screen"><PageHeader title="Wallet & loyalty" back={back}/><div className="wallet-card"><small>NEST. BALANCE</small><h1>₹1,240</h1><p>Available for your next booking</p><button>Add money <Plus/></button></div><div className="points-card"><div><small>LOYALTY POINTS</small><b>680 pts</b></div><span>₹68 value</span></div><SectionTitle title="Recent activity"/>{[["Booking cashback", "+ ₹120", "Today"], ["Deep cleaning", "− ₹2,548", "16 Sep"], ["Referral reward", "+ ₹250", "08 Sep"]].map(x => <div className="transaction" key={x[0]}><span className="menu-icon"><WalletCards/></span><div><b>{x[0]}</b><small>{x[2]}</small></div><strong>{x[1]}</strong></div>)}</div>; }
function ReferScreen({ back, notify }: PageProps) { return <div className="screen"><PageHeader title="Refer & earn" back={back}/><div className="refer-hero"><Gift/><small>GIVE ₹200, GET ₹200</small><h1>Good homes<br/>share good help.</h1><p>Invite friends to nest. They get ₹200 off and you earn ₹200 after their first service.</p></div><div className="referral-code"><span><small>YOUR CODE</small><b>AANYA200</b></span><button onClick={() => notify("Referral code copied")}>COPY</button></div><Button onClick={() => notify("Share sheet opened")}>Share invite</Button><SectionTitle title="How it works"/><ol className="steps"><li><span>1</span><p><b>Share your code</b><small>Send it to friends and family</small></p></li><li><span>2</span><p><b>They book a service</b><small>They save ₹200 on the first booking</small></p></li><li><span>3</span><p><b>You earn ₹200</b><small>Added to your nest. wallet</small></p></li></ol></div>; }

function SupportScreen({ back }: PageProps) { return <div className="screen"><PageHeader title="Help & support" back={back}/><div className="support-intro"><LifeBuoy/><h2>How can we help?</h2><p>Our care team usually replies within 5 minutes.</p></div>{[[Phone,"Call support","Available 8 AM – 10 PM"],[MessageCircle,"WhatsApp us","Fastest response"],[Inbox,"Email support","Replies within 24 hours"]].map(([Icon,title,text]) => <button className="support-card" key={title as string}><span className="menu-icon"><Icon/></span><div><b>{title as string}</b><small>{text as string}</small></div><ArrowRight/></button>)}<SectionTitle title="Popular topics"/><div className="menu-card">{["Reschedule a booking", "Refunds & cancellations", "Payments & invoices", "Service warranty"].map(x => <button key={x}><b>{x}</b><ChevronRight/></button>)}</div></div>; }
function AreasScreen({ back }: PageProps) { return <div className="screen"><PageHeader title="Service areas" back={back}/><div className="map-card"><div className="map-lines"/><MapPin/><b>We serve 24 areas</b><span>across Bengaluru</span></div><label className="search-input"><Search/><input placeholder="Search your area"/></label><SectionTitle title="Popular areas"/><div className="area-list">{["Indiranagar", "Koramangala", "HSR Layout", "Whitefield", "Jayanagar", "JP Nagar"].map(x => <button key={x}><MapPin/><b>{x}</b><span>Available</span><ChevronRight/></button>)}</div></div>; }
function AddressesScreen({ back, setSheet }: PageProps) { return <div className="screen"><PageHeader title="Saved addresses" back={back}/><div className="address-card"><span className="menu-icon"><Home/></span><div><b>Home</b><p>12, 3rd Cross Road, Indiranagar<br/>Bengaluru 560038</p><small>Aanya · +91 98765 43210</small></div><button>EDIT</button></div><div className="address-card"><span className="menu-icon"><Wrench/></span><div><b>Office</b><p>WeWork, Embassy Tech Village<br/>Bellandur, Bengaluru 560103</p></div><button>EDIT</button></div><Button variant="outline" onClick={() => setSheet("location")}><Plus/> Add a new address</Button></div>; }
function LanguageScreen({ back, notify }: PageProps) { const [lang, setLang] = useState("English"); return <div className="screen"><PageHeader title="Language" back={back}/><p className="page-lead">Choose the language you prefer for the app.</p><div className="language-list">{[["English","EN"],["हिन्दी","HI"],["বাংলা","BN"],["मराठी","MR"],["العربية","AR"]].map(([name,code]) => <button key={code} onClick={() => setLang(name)}><span>{code}</span><b>{name}</b><i className={lang === name ? "radio checked" : "radio"}>{lang === name && <Check/>}</i></button>)}</div><Button onClick={() => notify(`${lang} selected`)}>Save language</Button></div>; }

function AuthScreen({ mode, navigate }: PageProps & { mode: "signin" | "signup" }) { const signup = mode === "signup"; return <div className="auth-screen"><Brand/><div><small>{signup ? "CREATE YOUR ACCOUNT" : "WELCOME BACK"}</small><h1>{signup ? "Let's make home feel easy." : "Good to see you again."}</h1><p>{signup ? "Trusted home services are a few taps away." : "Sign in to manage your bookings and services."}</p></div>{signup && <FormField label="Full name" placeholder="Your full name"/>}<FormField label="Phone or email" placeholder="you@example.com"/><FormField label="Password" placeholder="••••••••"/>{signup && <FormField label="Referral code (optional)" placeholder="Enter code"/>}<Button onClick={() => navigate(signup ? "otp" : "location")}>{signup ? "Create account" : "Sign in"}</Button>{!signup && <button className="forgot-link" onClick={() => navigate("forgot")}>Forgot password?</button>}<div className="or"><span/>or continue with<span/></div><div className="socials"><button>G</button><button>●</button><button></button></div><p className="auth-switch">{signup ? "Already have an account?" : "New to nest.?"} <button onClick={() => navigate(signup ? "signin" : "signup")}>{signup ? "Sign in" : "Create account"}</button></p></div>; }
function OtpScreen({ back, navigate }: PageProps) { return <div className="auth-screen"><IconButton label="Back" onClick={back}><ArrowLeft/></IconButton><div><small>VERIFY NUMBER</small><h1>Enter the 6-digit code.</h1><p>We sent it to +91 98765 43210</p></div><div className="otp-inputs">{[1,2,3,4,5,6].map((x,i) => <input key={x} inputMode="numeric" maxLength={1} defaultValue={i < 4 ? String(i+2) : ""}/>)}</div><p className="center-note">Resend code in <b>00:28</b></p><Button onClick={() => navigate("location")}>Verify & continue</Button></div>; }
function ForgotScreen({ back, navigate }: PageProps) { return <div className="auth-screen"><IconButton label="Back" onClick={back}><ArrowLeft/></IconButton><div><small>RESET PASSWORD</small><h1>We'll help you get back in.</h1><p>Enter your registered email or phone number.</p></div><FormField label="Phone or email" placeholder="you@example.com"/><Button onClick={() => navigate("otp")}>Send verification code</Button></div>; }
function LocationScreen({ navigate }: PageProps) { return <div className="location-screen"><div className="fake-map"><div className="map-lines"/><div className="map-pin"><MapPin/></div><label className="map-search"><Search/><input placeholder="Search for your location"/></label><IconButton label="Use current location" filled><Navigation/></IconButton></div><div className="location-panel"><span className="grabber"/><small>SET YOUR LOCATION</small><h1>Services near you,<br/>right when you need them.</h1><p>We use your location to show available professionals and accurate pricing.</p><Button onClick={() => navigate("home")}><Navigation/> Use current location</Button><Button variant="outline" onClick={() => navigate("addresses")}>Set manually</Button></div></div>; }

function CategoriesScreen({ back, setCategory, navigate }: PageProps) { return <div className="screen"><PageHeader title="Available services" back={back}/><div className="big-categories">{categories.slice(0,7).map(({name,icon:Icon}) => <button key={name} onClick={() => {setCategory(name === "AC repair" ? "AC & Appliance" : name); navigate("services");}}><span><Icon/></span><b>{name}</b><small>8–24 services</small></button>)}</div><SectionTitle title="Sub-categories"/>{["Bathroom cleaning", "Kitchen cleaning", "Sofa & carpet care", "Move-in cleaning"].map(x => <button className="subcategory" key={x}><img src={cleaningImage} alt="Cleaning"/><div><b>{x}</b><span>Professional tools and supplies included</span><small>6 services</small></div><ChevronRight/></button>)}</div>; }
function PostScreen({ back, notify }: PageProps) { return <div className="screen"><PageHeader title="Create a request" back={back}/><Progress current={1}/><FormField label="What do you need?" placeholder="e.g. Paint my living room"/><label className="form-field"><span>Describe the work</span><textarea placeholder="Add measurements, condition, or anything professionals should know…"/></label><button className="upload-box"><Plus/><b>Add photos</b><span>Up to 5 images</span></button><FormField label="Preferred date" value="02 October 2026"/><FormField label="Address" value="Home · Indiranagar"/><Button onClick={() => notify("Request posted")}>Post request</Button></div>; }
function PostsScreen({ back, navigate }: PageProps) { return <div className="screen"><PageHeader title="My posts" back={back} action={<IconButton label="New post" onClick={() => navigate("post")}><Plus/></IconButton>}/><div className="post-card"><div><small>OPEN · 3 OFFERS</small><b>Paint my living room</b><p>Approx. 280 sq. ft. · Indiranagar</p></div><strong>From ₹4,500</strong><Button variant="outline">View offers</Button></div></div>; }
function PolicyScreen({ back }: PageProps) { return <div className="screen legal"><PageHeader title="About nest." back={back}/><h1>Care for every<br/>corner of home.</h1><p>nest. connects households with verified professionals for cleaning, repairs, maintenance and personal care.</p><h2>Our promise</h2><p>Transparent prices, qualified experts and real support from the moment you book until the job is complete.</p><h2>Terms & privacy</h2><p>Your bookings and personal information are used only to deliver and improve services. You remain in control of your preferences and account.</p><h2>Refund & cancellation</h2><p>Eligible refunds are returned to the original payment method. Cancellation charges may apply close to the scheduled time.</p></div>; }
function StatesScreen({ back }: PageProps) { const [state, setState] = useState("offline"); return <div className="screen"><PageHeader title="App states" back={back}/><div className="chips">{["offline","empty","loading","update"].map(x => <button className={state===x ? "chip active":"chip"} onClick={() => setState(x)} key={x}>{x}</button>)}</div>{state === "offline" && <Empty icon={Zap} title="You're offline" text="Check your connection and try again." action="Retry"/>}{state === "empty" && <Empty title="Nothing here yet" text="Your activity will appear here."/>}{state === "loading" && <div className="skeletons">{[1,2,3,4].map(x => <div key={x}><i/><span><b/><small/><small/></span></div>)}</div>}{state === "update" && <Empty icon={PackageCheck} title="A better nest. is ready" text="Update now for the latest improvements." action="Update app"/>}</div>; }

function Empty({ icon: Icon = Search, title, text, action }: {icon?: LucideIcon; title: string; text: string; action?: string}) { return <div className="empty"><span><Icon/></span><h2>{title}</h2><p>{text}</p>{action && <Button variant="outline">{action}</Button>}</div>; }
function BottomNav({ active, onChange, count }: { active: Tab; onChange: (t: Tab) => void; count: number }) { const tabs: Array<[Tab, LucideIcon, string]> = [["home",Home,"Home"],["services",Search,"Services"],["bookings",CalendarDays,"Bookings"],["cart",ShoppingBag,"Cart"],["account",UserRound,"Account"]]; return <nav className="bottom-nav">{tabs.map(([id, Icon, label]) => <button className={active === id ? "active" : ""} onClick={() => onChange(id)} key={id}><span><Icon/>{id === "cart" && count > 0 && <em>{count}</em>}</span><b>{label}</b></button>)}</nav>; }
function Sheet({ type, close, selectedService, setCartCount, cartCount, navigate, setQuery }: PageProps & { type: string; close: () => void }) { const [qty,setQty] = useState(1); return <div className="sheet-wrap" role="dialog" aria-modal="true" onMouseDown={(e) => {if(e.target === e.currentTarget) close();}}><div className="sheet"><span className="grabber"/><div className="sheet-head"><h2>{type === "search" ? "Find a service" : type === "location" ? "Choose location" : "Customize service"}</h2><IconButton label="Close" onClick={close}><X/></IconButton></div>{type === "search" && <><label className="search-input"><Search/><input autoFocus placeholder="Search services" onKeyDown={(e) => {if(e.key === "Enter"){setQuery((e.target as HTMLInputElement).value); close(); navigate("services");}}}/></label><SectionTitle title="Recent searches"/><div className="recent-searches">{["AC service", "Sofa cleaning", "Electrician"].map(x => <button key={x} onClick={() => {setQuery(x); close(); navigate("services");}}><Clock3/>{x}<ArrowRight/></button>)}</div><SectionTitle title="Recommended"/><div className="chips"><span className="chip">Deep cleaning</span><span className="chip">Salon at home</span><span className="chip">RO repair</span></div></>}{type === "location" && <><button className="current-location" onClick={() => {close(); navigate("location");}}><span><Navigation/></span><div><b>Use current location</b><small>Using GPS</small></div><ChevronRight/></button><SectionTitle title="Saved addresses"/><button className="selection-card selected" onClick={close}><span className="menu-icon"><Home/></span><div><b>Home</b><p>12, 3rd Cross Road, Indiranagar</p></div><Check/></button><button className="selection-card" onClick={close}><span className="menu-icon"><Wrench/></span><div><b>Office</b><p>Embassy Tech Village, Bellandur</p></div></button><Button variant="outline" onClick={() => {close(); navigate("addresses");}}>Manage addresses</Button></>}{type === "book" && <><div className="sheet-service"><img src={selectedService.image} alt={selectedService.name}/><div><small>{selectedService.category}</small><b>{selectedService.name}</b><span>₹{selectedService.price.toLocaleString("en-IN")}</span></div></div><SectionTitle title="Choose package"/><button className="selection-card selected"><span className="radio checked"><Check/></span><div><b>Standard service</b><p>Professional tools included · {selectedService.duration}</p></div><strong>₹{selectedService.price.toLocaleString("en-IN")}</strong></button><div className="quantity-row"><div><b>Quantity</b><span>Number of units</span></div><div className="stepper"><button onClick={() => setQty(Math.max(1, qty-1))}><Minus/></button><b>{qty}</b><button onClick={() => setQty(qty+1)}><Plus/></button></div></div><Button onClick={() => {setCartCount(cartCount + qty); close(); navigate("cart");}}>Add to cart · ₹{(selectedService.price*qty).toLocaleString("en-IN")}</Button></>}</div></div>; }