import { createFileRoute } from "@tanstack/react-router";
import {
  ArrowLeft, Bell, BriefcaseBusiness, CalendarDays, Camera, Check, CheckCircle2,
  ChevronRight, CircleUserRound, Clock3, FileText, Globe2, History, Image,
  IndianRupee, Languages, LifeBuoy, LockKeyhole, LogOut, Mail, MapPin, Menu,
  MessageCircle, Navigation, Paperclip, Phone, Plus, RefreshCw, Search, Send,
  Settings2, ShieldCheck, Smartphone, Star, UserRound, WalletCards, WifiOff,
  Wrench, X, Minus, Eye, EyeOff, Moon, Pencil, Download,
} from "lucide-react";
import { useEffect, useMemo, useState, type ReactNode } from "react";
import technicianPhoto from "../assets/technician-rahul.jpg";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "KaamPro — Service Partner" },
    { name: "description", content: "Bookings, customers, earnings and support for KaamPro service partners." },
    { property: "og:title", content: "KaamPro — Service Partner" },
    { property: "og:description", content: "A complete work app for service professionals." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ]}),
  component: App,
});

type Screen = "splash" | "language" | "signin" | "forgot" | "otp" | "password" | "dashboard" | "bookings" | "history" | "bookingDetails" | "bookingEdit" | "inbox" | "conversations" | "chat" | "profile" | "editProfile" | "notifications" | "menu" | "html" | "maintenance" | "update";
type Tab = "dashboard" | "bookings" | "inbox" | "profile";
type Booking = { id: string; time: string; date: string; title: string; customer: string; area: string; amount: string; status: string };

const bookings: Booking[] = [
  { id: "KP-1048", time: "10:30 AM", date: "Today", title: "AC Service & Cleaning", customer: "Anita Desai", area: "Andheri West", amount: "₹899", status: "Pending" },
  { id: "KP-1049", time: "12:00 PM", date: "Today", title: "Water Purifier Installation", customer: "Vikram Patel", area: "Bandra West", amount: "₹1,200", status: "Accepted" },
  { id: "KP-1050", time: "2:30 PM", date: "Today", title: "Roof Leak Repair", customer: "Meera Nair", area: "Juhu", amount: "₹1,450", status: "Ongoing" },
  { id: "KP-1036", time: "4:00 PM", date: "28 Sep", title: "AC Gas Refill", customer: "Rohan Mehta", area: "Powai", amount: "₹1,799", status: "Completed" },
  { id: "KP-1029", time: "11:00 AM", date: "26 Sep", title: "Fan Installation", customer: "Neha Shah", area: "Dadar", amount: "₹499", status: "Canceled" },
];

function App() {
  const [screen, setScreen] = useState<Screen>("splash");
  const [previous, setPrevious] = useState<Screen>("dashboard");
  const [online, setOnline] = useState(true);
  const [dark, setDark] = useState(false);
  const [notice, setNotice] = useState("");
  const [selected, setSelected] = useState<Booking>(bookings[0] ?? { id: "KP-1048", time: "10:30 AM", date: "Today", title: "AC Service & Cleaning", customer: "Anita Desai", area: "Andheri West", amount: "₹899", status: "Pending" });
  const [htmlTitle, setHtmlTitle] = useState("Terms & Conditions");

  useEffect(() => { const id = window.setTimeout(() => setScreen("dashboard"), 900); return () => window.clearTimeout(id); }, []);
  useEffect(() => { document.documentElement.classList.toggle("dark", dark); }, [dark]);

  const go = (next: Screen) => { setPrevious(screen); setScreen(next); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const back = () => setScreen(previous === screen ? "dashboard" : previous);
  const toast = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(""), 2200); };
  const openBooking = (booking: Booking) => { setSelected(booking); go("bookingDetails"); };
  const legal = (title: string) => { setHtmlTitle(title); go("html"); };

  if (screen === "splash") return <Splash />;

  const mainTabs: Screen[] = ["dashboard", "bookings", "inbox", "profile"];
  return <main className="min-h-screen bg-background font-body text-foreground">
    <div className="relative mx-auto flex min-h-screen w-full max-w-[430px] flex-col overflow-hidden border-x border-border bg-background shadow-panel">
      {screen === "language" && <Language onBack={back} onContinue={() => go("signin")} />}
      {screen === "signin" && <SignIn go={go} toast={toast} />}
      {screen === "forgot" && <Forgot go={go} />}
      {screen === "otp" && <Otp go={go} toast={toast} />}
      {screen === "password" && <NewPassword go={go} toast={toast} />}
      {screen === "dashboard" && <Dashboard online={online} setOnline={setOnline} go={go} openBooking={openBooking} toast={toast} />}
      {screen === "bookings" && <Bookings openBooking={openBooking} toast={toast} />}
      {screen === "history" && <HistoryView openBooking={openBooking} back={back} />}
      {screen === "bookingDetails" && <BookingDetails booking={selected} back={back} go={go} />}
      {screen === "bookingEdit" && <BookingEdit booking={selected} back={back} toast={toast} />}
      {screen === "inbox" && <Inbox go={go} />}
      {screen === "conversations" && <ConversationList go={go} back={back} />}
      {screen === "chat" && <Chat back={back} toast={toast} />}
      {screen === "profile" && <Profile online={online} setOnline={setOnline} dark={dark} setDark={setDark} go={go} />}
      {screen === "editProfile" && <EditProfile back={back} toast={toast} />}
      {screen === "notifications" && <Notifications back={back} toast={toast} />}
      {screen === "menu" && <MoreMenu back={back} go={go} legal={legal} />}
      {screen === "html" && <HtmlViewer title={htmlTitle} back={back} />}
      {screen === "maintenance" && <Maintenance go={go} />}
      {screen === "update" && <UpdateScreen back={back} toast={toast} />}
      {mainTabs.includes(screen) && <BottomNav active={screen as Tab} go={go} />}
      {notice && <div role="status" className="fixed bottom-24 left-1/2 z-50 max-w-[360px] -translate-x-1/2 rounded-md bg-primary px-4 py-3 text-center text-sm font-semibold text-primary-foreground shadow-panel animate-rise">{notice}</div>}
    </div>
  </main>;
}

function Splash() { return <main className="grid min-h-screen place-items-center bg-primary text-primary-foreground"><div className="text-center animate-rise"><div className="mx-auto grid size-20 place-items-center rounded-2xl bg-primary-foreground text-primary"><Wrench size={38} /></div><h1 className="mt-5 font-display text-4xl font-extrabold">KaamPro</h1><p className="mt-2 text-sm text-primary-foreground/60">Service Partner</p><div className="mx-auto mt-10 h-1 w-20 overflow-hidden rounded-full bg-primary-foreground/20"><span className="block h-full w-1/2 animate-loader bg-primary-foreground" /></div></div></main>; }

function PageHeader({ title, subtitle, onBack, right }: { title: string; subtitle?: string; onBack?: () => void; right?: ReactNode }) { return <header className="sticky top-0 z-20 flex min-h-20 items-center gap-3 border-b border-border bg-background/95 px-5 py-4 backdrop-blur-xl">{onBack && <Button size="icon" variant="ghost" onClick={onBack} aria-label="Go back"><ArrowLeft /></Button>}<div className="min-w-0 flex-1"><h1 className="truncate font-display text-xl font-bold">{title}</h1>{subtitle && <p className="mt-0.5 truncate text-xs text-muted-foreground">{subtitle}</p>}</div>{right}</header>; }
function Field({ label, placeholder, type = "text", prefix }: { label: string; placeholder: string; type?: string; prefix?: string }) { return <label className="block"><span className="mb-2 block text-xs font-semibold">{label}</span><div className="flex h-12 items-center rounded-md border border-input bg-card px-3">{prefix && <span className="mr-2 border-r border-border pr-2 text-sm font-semibold">{prefix}</span>}<Input type={type} placeholder={placeholder} className="h-auto border-0 px-0 shadow-none focus-visible:ring-0" /></div></label>; }
function AuthShell({ title, subtitle, children, back }: { title: string; subtitle: string; children: ReactNode; back?: () => void }) { return <section className="flex min-h-screen flex-col px-6 py-7 animate-rise">{back && <Button size="icon" variant="ghost" onClick={back} aria-label="Go back"><ArrowLeft /></Button>}<div className="mt-10"><div className="grid size-12 place-items-center rounded-lg bg-primary text-primary-foreground"><Wrench /></div><h1 className="mt-8 font-display text-3xl font-bold">{title}</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">{subtitle}</p></div><div className="mt-8 space-y-5">{children}</div></section>; }

function Language({ onBack, onContinue }: { onBack: () => void; onContinue: () => void }) { const [lang, setLang] = useState("English"); const languages = [{name:"English",code:"EN"},{name:"हिन्दी",code:"हि"},{name:"मराठी",code:"म"},{name:"ગુજરાતી",code:"ગુ"}]; return <section className="flex min-h-screen flex-col p-6"><Button size="icon" variant="ghost" onClick={onBack}><ArrowLeft /></Button><div className="mt-10"><Languages size={36} /><h1 className="mt-5 font-display text-3xl font-bold">Choose your language</h1><p className="mt-2 text-sm text-muted-foreground">You can change this anytime from your profile.</p></div><div className="mt-8 grid grid-cols-2 gap-3">{languages.map(({name,code}) => <Button key={name} variant={lang === name ? "default" : "outline"} onClick={() => setLang(name)} className="h-24 flex-col text-base"><span className="text-xl">{code}</span>{name}</Button>)}</div><Button size="lg" className="mt-auto h-12" onClick={onContinue}>Save & continue</Button></section>; }
function SignIn({ go, toast }: { go: (s: Screen) => void; toast: (s: string) => void }) { const [show, setShow] = useState(false); return <AuthShell title="Welcome back" subtitle="Sign in to manage your jobs and earnings."><Field label="Email or phone" placeholder="rahul@email.com" /><label className="block"><span className="mb-2 block text-xs font-semibold">Password</span><div className="flex h-12 items-center rounded-md border border-input bg-card px-3"><Input type={show ? "text" : "password"} placeholder="Minimum 8 characters" className="h-auto border-0 px-0 shadow-none focus-visible:ring-0"/><Button size="icon" variant="ghost" onClick={() => setShow(!show)} aria-label="Show password">{show ? <EyeOff/> : <Eye/>}</Button></div></label><div className="flex items-center justify-between text-xs"><label className="flex items-center gap-2"><input type="checkbox" defaultChecked className="accent-foreground"/> Remember me</label><Button variant="link" className="h-auto p-0 text-xs" onClick={() => go("forgot")}>Forgot password?</Button></div><Button className="h-12 w-full" onClick={() => { toast("Signed in successfully"); go("dashboard"); }}>Sign in</Button><Button variant="ghost" className="w-full" onClick={() => go("language")}><Globe2/> Change language</Button></AuthShell>; }
function Forgot({ go }: { go: (s: Screen) => void }) { return <AuthShell back={() => go("signin")} title="Forgot password?" subtitle="Enter your registered phone number. We’ll send a verification code."><div className="mx-auto grid size-24 place-items-center rounded-full bg-muted"><LockKeyhole size={38}/></div><Field label="Phone number" prefix="+91" placeholder="98765 43210" type="tel"/><Button className="h-12 w-full" onClick={() => go("otp")}>Send OTP</Button></AuthShell>; }
function Otp({ go, toast }: { go: (s: Screen) => void; toast: (s: string) => void }) { return <AuthShell back={() => go("forgot")} title="Enter verification code" subtitle="We sent a 6-digit code to +91 98••• ••210."><div className="grid grid-cols-6 gap-2">{[0,1,2,3,4,5].map((n) => <Input key={n} aria-label={`OTP digit ${n+1}`} maxLength={1} inputMode="numeric" className="h-12 p-0 text-center text-lg font-bold" />)}</div><p className="text-center text-xs text-muted-foreground">Resend code in <strong className="text-foreground">00:28</strong></p><Button className="h-12 w-full" onClick={() => go("password")}>Verify code</Button><Button variant="link" className="w-full" onClick={() => toast("A new code has been sent")}>Resend code</Button></AuthShell>; }
function NewPassword({ go, toast }: { go: (s: Screen) => void; toast: (s: string) => void }) { return <AuthShell back={() => go("otp")} title="Create new password" subtitle="Use at least 8 characters for a secure password."><Field label="New password" placeholder="Enter new password" type="password"/><Field label="Confirm password" placeholder="Re-enter password" type="password"/><Button className="h-12 w-full" onClick={() => { toast("Password changed"); go("signin"); }}>Change password</Button></AuthShell>; }

function Dashboard({ online, setOnline, go, openBooking, toast }: { online: boolean; setOnline: (v:boolean)=>void; go:(s:Screen)=>void; openBooking:(b:Booking)=>void; toast:(s:string)=>void }) {
  const greeting = useMemo(() => new Date().getHours() < 12 ? "Good morning" : new Date().getHours() < 17 ? "Good afternoon" : "Good evening", []);
  return <div className="pb-28"><header className="flex items-center justify-between px-5 py-5"><button className="flex min-w-0 items-center gap-3 text-left" onClick={() => go("profile")}><Avatar online={online}/><span><span className="block text-[11px] text-muted-foreground">{greeting}</span><strong className="font-display text-base">Rahul Sharma</strong><span className="ml-2 rounded-sm bg-muted px-1.5 py-0.5 text-[9px] font-bold">PRO</span></span></button><div className="flex gap-1"><Button size="icon" variant="ghost" onClick={() => go("notifications")} aria-label="Notifications"><Bell/></Button><Button size="icon" variant="ghost" onClick={() => go("menu")} aria-label="Menu"><Menu/></Button></div></header>
  <section className="px-5"><div className="flex items-center justify-between rounded-md bg-primary p-4 text-primary-foreground"><div><p className="text-xs text-primary-foreground/60">Work availability</p><p className="mt-1 font-display text-lg font-bold">{online ? "You’re online" : "You’re offline"}</p></div><Button onClick={() => setOnline(!online)} className={online ? "bg-success text-primary-foreground hover:bg-success/90" : "bg-primary-foreground text-primary"}><span className="size-2 rounded-full bg-current"/>{online ? "Online" : "Go online"}</Button></div></section>
  <section className="mt-4 grid grid-cols-3 gap-2 px-5"><Stat label="Assigned" value="4"/><Stat label="Ongoing" value="1" success/><Stat label="Completed" value="26"/></section>
  <section className="mt-6 px-5"><div className="mb-3 flex items-center justify-between"><h2 className="font-display text-lg font-bold">Quick actions</h2></div><div className="grid grid-cols-4 gap-2">{[[BriefcaseBusiness,"Requests","bookings"],[History,"History","history"],[Mail,"Inbox","inbox"],[Bell,"Alerts","notifications"]].map(([Icon,label,target]) => { const C = Icon as typeof Bell; return <Button key={label as string} variant="outline" onClick={() => go(target as Screen)} className="h-20 flex-col px-1 text-[11px]"><C/>{label as string}</Button>; })}</div></section>
  <section className="mt-6 px-5"><div className="rounded-md border border-border bg-card p-5"><div className="flex items-center justify-between"><div><p className="text-xs text-muted-foreground">This month</p><p className="mt-1 font-display text-3xl font-bold">₹38,640</p></div><span className="rounded-sm bg-success-soft px-2 py-1 text-xs font-bold text-success">+18%</span></div><div className="mt-5 flex h-14 items-end gap-2">{[40,64,48,76,55,88,70,100].map((h,i)=><span key={i} className={`flex-1 rounded-sm ${i===7?"bg-foreground":"bg-muted"}`} style={{height:`${h}%`}}/>)}</div></div></section>
  <section className="mt-6 px-5"><div className="mb-3 flex items-center justify-between"><h2 className="font-display text-lg font-bold">Recent bookings</h2><Button variant="link" className="h-auto p-0 text-xs" onClick={() => go("bookings")}>See all <ChevronRight/></Button></div><div className="space-y-3">{bookings.slice(0,2).map(b=><BookingCard key={b.id} booking={b} onClick={()=>openBooking(b)}/>)}</div></section>
  <Button className="mx-5 mt-5 w-[calc(100%-2.5rem)]" variant="outline" onClick={()=>toast("Dashboard refreshed")}><RefreshCw/> Refresh dashboard</Button></div>;
}

function Bookings({ openBooking, toast }: { openBooking:(b:Booking)=>void; toast:(s:string)=>void }) { const [filter,setFilter]=useState("Pending"); const filtered=bookings.filter(b=>filter==="All"||b.status===filter); return <section className="pb-28"><PageHeader title="Bookings" subtitle={`${bookings.length} total · ${filtered.length} matched`} right={<Button size="icon" variant="ghost" onClick={()=>toast("Bookings refreshed")}><RefreshCw/></Button>}/><div className="flex gap-2 overflow-x-auto px-5 py-4">{["All","Pending","Accepted","Ongoing","Completed","Canceled"].map(f=><Button key={f} size="sm" variant={filter===f?"default":"outline"} onClick={()=>setFilter(f)} className="shrink-0">{f}</Button>)}</div><div className="space-y-3 px-5">{filtered.length ? filtered.map(b=><BookingCard key={b.id} booking={b} onClick={()=>openBooking(b)} actions/>) : <Empty icon={<BriefcaseBusiness/>} title="No bookings here" text="New bookings will appear in this list."/>}</div></section>; }
function HistoryView({ openBooking, back }: { openBooking:(b:Booking)=>void; back:()=>void }) { const [filter,setFilter]=useState("All"); const past=bookings.filter(b=>["Completed","Canceled"].includes(b.status)).filter(b=>filter==="All"||b.status===filter); return <section><PageHeader title="Booking history" subtitle="2 past bookings" onBack={back}/><div className="grid grid-cols-3 gap-2 px-5 py-4"><Stat label="All" value="32"/><Stat label="Completed" value="26"/><Stat label="Canceled" value="6"/></div><div className="flex gap-2 px-5 pb-4">{["All","Completed","Canceled"].map(f=><Button key={f} size="sm" variant={filter===f?"default":"outline"} onClick={()=>setFilter(f)}>{f}</Button>)}</div><div className="space-y-3 px-5">{past.map(b=><BookingCard key={b.id} booking={b} onClick={()=>openBooking(b)}/>)}</div></section>; }
function BookingCard({ booking, onClick, actions=false }: { booking:Booking; onClick:()=>void; actions?:boolean }) { return <div className="rounded-md border border-border bg-card p-4"><button className="w-full text-left" onClick={onClick}><div className="flex items-center justify-between"><Status status={booking.status}/><span className="text-xs font-semibold text-muted-foreground">{booking.id}</span></div><h3 className="mt-3 font-display text-base font-bold">{booking.title}</h3><p className="mt-2 flex items-center gap-2 text-xs text-muted-foreground"><UserRound size={14}/>{booking.customer}</p><p className="mt-2 flex items-center gap-2 text-xs text-muted-foreground"><CalendarDays size={14}/>{booking.date}, {booking.time}<span>·</span><MapPin size={14}/>{booking.area}</p><div className="mt-3 border-t border-border pt-3 text-right font-display font-bold">{booking.amount}</div></button>{actions&&booking.status==="Pending"&&<div className="mt-3 grid grid-cols-2 gap-2"><Button variant="outline">Decline</Button><Button>Accept job</Button></div>}</div>; }
function BookingDetails({ booking, back, go }: { booking:Booking; back:()=>void; go:(s:Screen)=>void }) { const [tab,setTab]=useState("Details"); return <section className="pb-24"><PageHeader title="Booking details" subtitle={booking.id} onBack={back} right={<Button size="icon" variant="ghost" onClick={()=>go("bookingEdit")}><Pencil/></Button>}/><div className="grid grid-cols-2 border-b border-border px-5">{["Details","Status"].map(t=><Button key={t} variant="ghost" onClick={()=>setTab(t)} className={`rounded-none border-b-2 ${tab===t?"border-foreground":"border-transparent text-muted-foreground"}`}>{t}</Button>)}</div>{tab==="Details"?<div className="space-y-4 p-5"><section className="rounded-md bg-primary p-5 text-primary-foreground"><Status status={booking.status}/><h2 className="mt-4 font-display text-xl font-bold">{booking.title}</h2><p className="mt-1 text-sm text-primary-foreground/60">Standard service · 1 unit</p></section><Info title="Customer" rows={[[UserRound,booking.customer],[Phone,"+91 98765 43210"]]}/><Info title="Schedule & address" rows={[[Clock3,`${booking.date}, ${booking.time}`],[MapPin,`12, Palm Residency, ${booking.area}, Mumbai`]]}/><Info title="Payment" rows={[[WalletCards,"Cash after service"],[IndianRupee,`${booking.amount} · Unpaid`]]}/><div className="grid grid-cols-2 gap-2"><Button variant="outline" asChild><a href="tel:+919876543210"><Phone/>Call customer</a></Button><Button><Navigation/>Directions</Button></div></div>:<Timeline/>}<Button onClick={()=>go("chat")} size="icon" className="fixed bottom-6 right-[max(1.25rem,calc((100vw-430px)/2+1.25rem))] size-14 rounded-full shadow-panel" aria-label="Chat with customer"><MessageCircle/></Button></section>; }
function BookingEdit({ booking, back, toast }: { booking:Booking; back:()=>void; toast:(s:string)=>void }) { const [qty,setQty]=useState(1); return <section><PageHeader title="Update booking" subtitle={booking.id} onBack={back}/><div className="space-y-5 p-5"><div className="flex items-center justify-between rounded-md border border-border p-4"><span><strong className="block text-sm">Payment status</strong><small className="text-muted-foreground">Cash payment pending</small></span><Button size="sm" variant="outline">Mark paid</Button></div><label className="block text-xs font-semibold">Booking status<select className="mt-2 h-12 w-full rounded-md border border-input bg-card px-3 text-sm"><option>Accepted</option><option>Ongoing</option><option>Completed</option><option>Canceled</option></select></label><div className="grid grid-cols-2 gap-3"><Field label="Service date" placeholder="01 Oct 2026"/><Field label="Time" placeholder="10:30 AM"/></div><div><div className="flex items-center justify-between"><h2 className="font-display font-bold">Services</h2><Button size="sm" variant="outline"><Plus/> Add</Button></div><div className="mt-3 rounded-md border border-border p-4"><h3 className="font-semibold">AC Service & Cleaning</h3><p className="mt-1 text-xs text-muted-foreground">Standard · ₹899 each</p><div className="mt-4 flex items-center justify-between"><div className="flex items-center gap-2"><Button size="icon" variant="outline" onClick={()=>setQty(Math.max(1,qty-1))}><Minus/></Button><strong className="w-6 text-center">{qty}</strong><Button size="icon" variant="outline" onClick={()=>setQty(qty+1)}><Plus/></Button></div><Button size="sm" variant="ghost" className="text-destructive"><X/> Remove</Button></div></div></div><Button className="h-12 w-full" onClick={()=>toast("Booking updated")}>Update booking</Button></div></section>; }

const chats=[{name:"Anita Desai",msg:"Please call when you arrive",time:"9:42 AM",count:2,type:"Customer"},{name:"Vikram Patel",msg:"Address shared. Thank you!",time:"Yesterday",count:0,type:"Customer"},{name:"KaamPro Support",msg:"Your payout has been processed",time:"Mon",count:1,type:"Provider"}];
function Inbox({ go }: { go:(s:Screen)=>void }) { const [search,setSearch]=useState(""); const [filter,setFilter]=useState("All"); const shown=chats.filter(c=>(filter==="All"||c.type===filter)&&c.name.toLowerCase().includes(search.toLowerCase())); return <section className="pb-28"><PageHeader title="Inbox" subtitle="3 conversations" right={<Button size="icon" variant="ghost" onClick={()=>go("conversations")}><Settings2/></Button>}/><div className="p-5"><label className="flex h-11 items-center gap-2 rounded-md border border-input px-3"><Search/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search conversations" className="border-0 px-0 shadow-none focus-visible:ring-0"/></label><div className="mt-3 flex gap-2">{["All","Customer","Provider"].map(f=><Button key={f} size="sm" variant={filter===f?"default":"outline"} onClick={()=>setFilter(f)}>{f}</Button>)}</div><div className="mt-4 divide-y divide-border">{shown.map(c=><ChatRow key={c.name} {...c} onClick={()=>go("chat")}/>)}</div></div></section>; }
function ConversationList({ go, back }: { go:(s:Screen)=>void; back:()=>void }) { const [tab,setTab]=useState("Customer"); return <section><PageHeader title="Conversations" subtitle="Customers and support" onBack={back}/><div className="p-5"><label className="flex h-11 items-center gap-2 rounded-md border border-input px-3"><Search/><Input placeholder="Search by name" className="border-0 px-0 shadow-none focus-visible:ring-0"/></label><button onClick={()=>go("chat")} className="mt-4 flex w-full items-center gap-3 rounded-md bg-primary p-4 text-left text-primary-foreground"><span className="grid size-11 place-items-center rounded-full bg-primary-foreground text-primary"><LifeBuoy/></span><span className="flex-1"><strong className="block">KaamPro Support</strong><small className="text-primary-foreground/60">Usually replies in a few minutes</small></span><ChevronRight/></button><div className="mt-5 grid grid-cols-2 border-b border-border">{["Customer","Provider"].map(t=><Button key={t} variant="ghost" onClick={()=>setTab(t)} className={`rounded-none border-b-2 ${tab===t?"border-foreground":"border-transparent"}`}>{t}</Button>)}</div><div className="divide-y divide-border">{chats.filter(c=>c.type===tab).map(c=><ChatRow key={c.name} {...c} onClick={()=>go("chat")}/>)}</div></div></section>; }
function ChatRow({name,msg,time,count,onClick}:{name:string;msg:string;time:string;count:number;type?:string;onClick:()=>void}) { return <button onClick={onClick} className="flex w-full items-center gap-3 py-4 text-left"><span className="grid size-11 shrink-0 place-items-center rounded-full bg-muted font-bold">{name[0]}</span><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{name}</strong><small className="block truncate text-muted-foreground">{msg}</small></span><span className="text-right"><small className="block text-[10px] text-muted-foreground">{time}</small>{count>0&&<b className="ml-auto mt-1 grid size-5 place-items-center rounded-full bg-primary text-[10px] text-primary-foreground">{count}</b>}</span></button>; }
function Chat({ back, toast }: { back:()=>void; toast:(s:string)=>void }) { const [text,setText]=useState(""); const [messages,setMessages]=useState(["Hi Rahul, is the 10:30 slot confirmed?","Yes, I’ll reach by 10:25 AM.","Perfect. Please call when you arrive."]); const send=()=>{if(text.trim()){setMessages([...messages,text]);setText("");}}; return <section className="flex min-h-screen flex-col"><PageHeader title="Anita Desai" subtitle="Online" onBack={back} right={<Button size="icon" variant="ghost" asChild><a href="tel:+919876543210"><Phone/></a></Button>}/><div className="flex-1 space-y-3 p-5">{messages.map((m,i)=><div key={`${m}-${i}`} className={`max-w-[82%] rounded-md px-3 py-2 text-sm ${i%2?"ml-auto bg-primary text-primary-foreground":"bg-muted"}`}><p>{m}</p><small className={`mt-1 block text-right text-[9px] ${i%2?"text-primary-foreground/55":"text-muted-foreground"}`}>{i%2?"9:40 AM · Read":"9:38 AM"}</small></div>)}</div><div className="sticky bottom-0 flex items-center gap-2 border-t border-border bg-background p-3"><Button size="icon" variant="ghost" onClick={()=>toast("Choose an image or file")}><Paperclip/></Button><Input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")send();}} placeholder="Type a message…" className="h-11"/><Button size="icon" onClick={send}><Send/></Button></div></section>; }

function Profile({ online,setOnline,dark,setDark,go }:{online:boolean;setOnline:(v:boolean)=>void;dark:boolean;setDark:(v:boolean)=>void;go:(s:Screen)=>void}) { return <section className="pb-28"><div className="bg-primary px-5 pb-7 pt-5 text-primary-foreground"><div className="flex justify-between"><Button size="icon" variant="ghost" onClick={()=>go("menu")} className="text-primary-foreground hover:bg-primary-foreground/10"><Menu/></Button><Button size="icon" variant="ghost" onClick={()=>go("editProfile")} className="text-primary-foreground hover:bg-primary-foreground/10"><Pencil/></Button></div><div className="mt-2 flex flex-col items-center"><Avatar large online={online}/><h1 className="mt-3 font-display text-2xl font-bold">Rahul Sharma</h1><p className="text-sm text-primary-foreground/60">AC & Cooling Expert</p><span className="mt-2 rounded-sm bg-primary-foreground/10 px-2 py-1 text-[10px] font-bold">SERVICE PROFESSIONAL</span></div><div className="mt-6 grid grid-cols-3 divide-x divide-primary-foreground/20 text-center"><MiniStat label="Days joined" value="186"/><MiniStat label="Completed" value="126"/><MiniStat label="Total jobs" value="138"/></div></div><div className="space-y-5 p-5"><div className="rounded-md border border-border bg-card p-4"><ToggleRow title="Available for jobs" text="Receive new service requests" value={online} onChange={()=>setOnline(!online)}/></div><MenuGroup title="Settings" items={[[UserRound,"Edit profile",()=>go("editProfile")],[Bell,"Notifications",()=>go("notifications")],[Moon,"Dark mode",()=>setDark(!dark)],[Languages,"Language",()=>go("language")]]}/><MenuGroup title="Support" items={[[FileText,"Terms & Conditions",()=>go("html")],[ShieldCheck,"Privacy policy",()=>go("html")],[LifeBuoy,"Help & support",()=>go("inbox")]]}/></div></section>; }
function EditProfile({ back, toast }:{back:()=>void;toast:(s:string)=>void}) { const [tab,setTab]=useState("General info"); return <section><PageHeader title="Edit profile" subtitle="Keep your details up to date" onBack={back}/><div className="grid grid-cols-2 border-b border-border px-5">{["General info","Account info"].map(t=><Button key={t} variant="ghost" onClick={()=>setTab(t)} className={`rounded-none border-b-2 ${tab===t?"border-foreground":"border-transparent"}`}>{t}</Button>)}</div><div className="space-y-5 p-5">{tab==="General info"?<><div className="mx-auto w-fit"><Avatar large/><Button size="icon" className="-mt-8 ml-16 rounded-full"><Camera/></Button></div><div className="grid grid-cols-2 gap-3"><Field label="First name" placeholder="Rahul"/><Field label="Last name" placeholder="Sharma"/></div><Field label="Phone" placeholder="98765 43210" prefix="+91"/><Field label="Email" placeholder="rahul.sharma@email.com" type="email"/></>:<><label className="block text-xs font-semibold">Identity type<select className="mt-2 h-12 w-full rounded-md border border-input bg-card px-3 text-sm"><option>Aadhaar card</option><option>PAN card</option><option>Driving licence</option></select></label><Field label="Identity number" placeholder="•••• •••• 4821"/><Field label="Address" placeholder="Andheri West, Mumbai"/><Field label="Service area" placeholder="Mumbai Western Suburbs"/></>}<Button className="h-12 w-full" onClick={()=>toast("Profile saved")}>Save changes</Button></div></section>; }
function Notifications({ back,toast }:{back:()=>void;toast:(s:string)=>void}) { const notes=[{day:"Today",title:"New booking assigned",text:"AC Service & Cleaning at Andheri West.",time:"9:15 AM"},{day:"Today",title:"Payment received",text:"₹1,200 was added to your earnings.",time:"8:40 AM"},{day:"Yesterday",title:"Great work!",text:"Vikram rated your service 5 stars.",time:"6:20 PM"}]; return <section><PageHeader title="Notifications" subtitle="3 updates" onBack={back} right={<Button size="icon" variant="ghost" onClick={()=>toast("Notifications refreshed")}><RefreshCw/></Button>}/><div className="p-5">{["Today","Yesterday"].map(day=><div key={day} className="mb-6"><h2 className="mb-2 text-xs font-bold uppercase text-muted-foreground">{day}</h2><div className="divide-y divide-border">{notes.filter(n=>n.day===day).map(n=><button key={n.title} onClick={()=>toast(n.text)} className="flex w-full gap-3 py-4 text-left"><span className="grid size-11 shrink-0 place-items-center rounded-md bg-muted"><Bell/></span><span className="flex-1"><strong className="text-sm">{n.title}</strong><p className="mt-1 line-clamp-2 text-xs leading-5 text-muted-foreground">{n.text}</p></span><small className="text-[10px] text-muted-foreground">{n.time}</small></button>)}</div></div>)}</div></section>; }
function MoreMenu({ back,go,legal }:{back:()=>void;go:(s:Screen)=>void;legal:(s:string)=>void}) { return <section className="min-h-screen bg-primary/40 pt-20"><div className="min-h-[calc(100vh-5rem)] rounded-t-2xl bg-background p-5 animate-rise"><div className="flex items-center justify-between"><div><h1 className="font-display text-2xl font-bold">More</h1><p className="text-xs text-muted-foreground">Account, support and app settings</p></div><Button size="icon" variant="ghost" onClick={back}><X/></Button></div><div className="mt-6"><MenuGroup title="Settings" items={[[CircleUserRound,"Profile",()=>go("profile")],[Languages,"Language",()=>go("language")],[Mail,"Inbox",()=>go("inbox")]]}/><div className="mt-5"><MenuGroup title="Support" items={[[FileText,"About KaamPro",()=>legal("About KaamPro")],[FileText,"Terms & Conditions",()=>legal("Terms & Conditions")],[ShieldCheck,"Privacy Policy",()=>legal("Privacy Policy")],[FileText,"Cancellation Policy",()=>legal("Cancellation Policy")],[IndianRupee,"Refund Policy",()=>legal("Refund Policy")]]}/></div><div className="mt-5"><MenuGroup title="App" items={[[Wrench,"Service status",()=>go("maintenance")],[Smartphone,"App update",()=>go("update")]]}/></div><Button variant="outline" className="mt-6 h-12 w-full text-destructive" onClick={()=>go("signin")}><LogOut/> Log out</Button></div></div></section>; }
function HtmlViewer({title,back}:{title:string;back:()=>void}) { return <section><PageHeader title={title} subtitle="KaamPro support and policies" onBack={back}/><div className="p-5"><div className="grid h-36 place-items-center rounded-md bg-primary text-primary-foreground"><FileText size={44}/></div><article className="prose mt-6 text-sm leading-7 text-muted-foreground"><h2 className="font-display text-xl font-bold text-foreground">{title}</h2><p>Welcome to KaamPro. This page explains the guidelines that apply when service professionals accept and complete customer bookings.</p><h3 className="mt-5 font-bold text-foreground">Service commitment</h3><p>Arrive on time, verify the requested work before starting, and keep the customer informed about any changes in cost or schedule.</p><h3 className="mt-5 font-bold text-foreground">Payments and safety</h3><p>Collect only the amount shown in the booking. Protect customer information and contact support whenever a booking feels unsafe or unclear.</p><a className="mt-5 inline-block font-semibold text-foreground underline" href="mailto:support@kaampro.example">Contact support</a></article></div></section>; }
function Maintenance({go}:{go:(s:Screen)=>void}) { return <section className="grid min-h-screen place-items-center p-8 text-center"><div><div className="mx-auto grid size-28 place-items-center rounded-full bg-muted"><Wrench size={46}/></div><h1 className="mt-7 font-display text-3xl font-bold">We’ll be back shortly</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">KaamPro is under scheduled maintenance. Your bookings and earnings are safe.</p><Button className="mt-7" onClick={()=>go("dashboard")}><RefreshCw/> Check again</Button></div></section>; }
function UpdateScreen({back,toast}:{back:()=>void;toast:(s:string)=>void}) { return <section className="grid min-h-screen place-items-center p-8 text-center"><div><div className="mx-auto grid size-28 place-items-center rounded-full bg-primary text-primary-foreground"><Download size={46}/></div><h1 className="mt-7 font-display text-3xl font-bold">Update KaamPro</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">A newer version is ready with important improvements for bookings and payments.</p><Button className="mt-7 h-12 w-full" onClick={()=>toast("Opening app store")}>Update now</Button><Button variant="ghost" className="mt-2 w-full" onClick={back}>Maybe later</Button></div></section>; }

function BottomNav({active,go}:{active:Tab;go:(s:Screen)=>void}) { const tabs:[[Tab,typeof Clock3,string],...Array<[Tab,typeof Clock3,string]>]=[["dashboard",Clock3,"Today"],["bookings",BriefcaseBusiness,"Bookings"],["inbox",Mail,"Inbox"],["profile",CircleUserRound,"Profile"]]; return <nav className="fixed bottom-0 left-1/2 z-40 grid w-full max-w-[430px] -translate-x-1/2 grid-cols-4 border-t border-border bg-background/95 px-3 pb-3 pt-2 backdrop-blur-xl">{tabs.map(([id,Icon,label])=><Button key={id} variant="ghost" onClick={()=>go(id)} className={`h-14 flex-col gap-1 rounded-md text-[10px] ${active===id?"bg-primary text-primary-foreground hover:bg-primary hover:text-primary-foreground":"text-muted-foreground"}`}><Icon/>{label}</Button>)}</nav>; }
function Avatar({large=false,online=false}:{large?:boolean;online?:boolean}) { return <span className="relative shrink-0"><img src={technicianPhoto} alt="Rahul Sharma" width={512} height={512} className={`${large?"size-24":"size-11"} rounded-full object-cover ring-2 ring-card`}/>{online&&<span className="absolute bottom-0 right-0 size-3 rounded-full bg-success ring-2 ring-background animate-status"/>}</span>; }
function Stat({label,value,success=false}:{label:string;value:string;success?:boolean}) { return <div className="rounded-md border border-border bg-card p-3"><p className="text-[10px] text-muted-foreground">{label}</p><p className={`mt-1 font-display text-xl font-bold ${success?"text-success":""}`}>{value}</p></div>; }
function MiniStat({label,value}:{label:string;value:string}) { return <div><strong className="block font-display text-lg">{value}</strong><span className="text-[10px] text-primary-foreground/55">{label}</span></div>; }
function Status({status}:{status:string}) { const live=status==="Ongoing"; return <span className={`inline-flex items-center gap-1 rounded-sm px-2 py-1 text-[10px] font-bold ${live?"bg-success-soft text-success":"bg-muted text-foreground"}`}><span className={`size-1.5 rounded-full ${live?"bg-success":"bg-current"}`}/>{status}</span>; }
function Info({title,rows}:{title:string;rows:Array<[typeof UserRound,string]>}) { return <section className="rounded-md border border-border bg-card p-4"><h3 className="text-xs font-bold uppercase text-muted-foreground">{title}</h3><div className="mt-3 space-y-3">{rows.map(([Icon,text])=><p key={text} className="flex items-start gap-3 text-sm"><Icon className="mt-0.5 shrink-0 text-muted-foreground" size={16}/><span>{text}</span></p>)}</div></section>; }
function Timeline() { return <div className="p-5">{[["Booking assigned","Today, 8:12 AM",true],["Booking accepted","Today, 8:20 AM",true],["Service started","Waiting for update",false],["Service completed","Pending",false]].map(([title,time,done],i)=><div key={title as string} className="flex gap-3"><div className="flex flex-col items-center"><span className={`grid size-7 place-items-center rounded-full ${done?"bg-success text-primary-foreground":"border border-border bg-card"}`}>{done?<Check size={14}/>:i+1}</span>{i<3&&<span className="h-12 w-px bg-border"/>}</div><div><strong className="text-sm">{title as string}</strong><p className="text-xs text-muted-foreground">{time as string}</p></div></div>)}</div>; }
function ToggleRow({title,text,value,onChange}:{title:string;text:string;value:boolean;onChange:()=>void}) { return <div className="flex items-center justify-between gap-3"><div><strong className="text-sm">{title}</strong><p className="text-xs text-muted-foreground">{text}</p></div><Button role="switch" aria-checked={value} onClick={onChange} className={`relative h-7 w-12 rounded-full p-0 ${value?"bg-success hover:bg-success":"bg-muted hover:bg-muted"}`}><span className={`absolute top-1 size-5 rounded-full bg-card shadow-sm transition-all ${value?"left-6":"left-1"}`}/></Button></div>; }
function MenuGroup({title,items}:{title:string;items:Array<[typeof UserRound,string,()=>void]>}) { return <section><h2 className="mb-2 text-xs font-bold uppercase text-muted-foreground">{title}</h2><div className="divide-y divide-border rounded-md border border-border bg-card">{items.map(([Icon,label,action])=><Button key={label} variant="ghost" onClick={action} className="h-14 w-full justify-start rounded-none px-4"><Icon/><span className="flex-1 text-left">{label}</span><ChevronRight className="text-muted-foreground"/></Button>)}</div></section>; }
function Empty({icon,title,text}:{icon:ReactNode;title:string;text:string}) { return <div className="py-16 text-center"><div className="mx-auto grid size-14 place-items-center rounded-full bg-muted">{icon}</div><h3 className="mt-4 font-display font-bold">{title}</h3><p className="mt-1 text-xs text-muted-foreground">{text}</p></div>; }
